name: aura
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  intl: ^0.19.0
  uuid: ^4.5.1
  logging: ^1.3.0
  path: ^1.9.0
  remixicon: ^1.3.0
  lottie: ^3.3.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - lib/presentation/animations/
    - lib/presentation/animations/think.json
    - lib/presentation/animations/search.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Black.ttf
        - weight: 900
        - asset: assets\fonts\Montserrat-ExtraBold.ttf
        - weight: 800
        - asset: assets\fonts\Montserrat-Bold.ttf
        - weight: 700
        - asset: assets\fonts\Montserrat-SemiBold.ttf
        - weight: 600
        - asset: assets\fonts\Montserrat-Medium.ttf
        - weight: 500
        - asset: assets\fonts\Montserrat-Regular.ttf
        - weight: 400
        - asset: assets\fonts\Montserrat-Light.ttf
        - weight: 300
        - asset: assets\fonts\Montserrat-ExtraLight.ttf
        - weight: 200
        - asset: assets\fonts\Montserrat-Thin.ttf
        - weight: 100
